# Copyright lowRISC contributors.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Cancel existing runs if a pull request is pushed.
# For branch pushes, this will queue a new run and cancel the existing one. This allows the cache
# of the run to be used by the new run.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  checks:
    name: Quality Check
    runs-on: nixos
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Nix Format Check
        run: nix fmt -- . --check --exclude ./third_party --exclude ./cheriot-rtos

      - name: Run Lints
        run: nix run .#lint-all

      - name: Build Software
        run: |
          nix build -L .#sonata-exercises
          nix build -L .#sonata-examples
          nix build -L .#sonata-automotive-demo-legacy-component
          nix build -L .#sonata-heartbleed-demo-legacy-component
          nix build -L .#sonata-tests

      - name: Run Nix Checks
        run: nix flake check -L .#
